package com.dynastech.system.entity;

import java.io.Serializable;
import java.util.List;

public class Resource implements Serializable{
	private static final long serialVersionUID = 5202827609486262746L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.name
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.type
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.url
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.parent_id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.parent_ids
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.permission
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.isdeleted
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private Boolean isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.className
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_resource.orderNo
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    private Integer orderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.id
     *
     * @return the value of RS_resource.id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.id
     *
     * @param id the value for RS_resource.id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.name
     *
     * @return the value of RS_resource.name
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.name
     *
     * @param name the value for RS_resource.name
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.type
     *
     * @return the value of RS_resource.type
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.type
     *
     * @param type the value for RS_resource.type
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.url
     *
     * @return the value of RS_resource.url
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.url
     *
     * @param url the value for RS_resource.url
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.parent_id
     *
     * @return the value of RS_resource.parent_id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.parent_id
     *
     * @param parentId the value for RS_resource.parent_id
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.parent_ids
     *
     * @return the value of RS_resource.parent_ids
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.parent_ids
     *
     * @param parentIds the value for RS_resource.parent_ids
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.permission
     *
     * @return the value of RS_resource.permission
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.permission
     *
     * @param permission the value for RS_resource.permission
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.isdeleted
     *
     * @return the value of RS_resource.isdeleted
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.isdeleted
     *
     * @param isdeleted the value for RS_resource.isdeleted
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.className
     *
     * @return the value of RS_resource.className
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.className
     *
     * @param classname the value for RS_resource.className
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_resource.orderNo
     *
     * @return the value of RS_resource.orderNo
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_resource.orderNo
     *
     * @param orderno the value for RS_resource.orderNo
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }
    
    
    
    
    
    
    
    
    
    
    List<Resource> childResource;
    
    public List<Resource> getChildResource() {
		return childResource;
	}
    
    public void setChildResource(List<Resource> childResource) {
		this.childResource = childResource;
	}
}