package com.dynastech.model.mapper;

import com.dynastech.model.entity.Apply;
import com.dynastech.model.entity.ApplyExample;
import com.dynastech.model.entity.ApplyWithEval;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int countByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int deleteByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    List<Apply> selectByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    Apply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") Apply record, @Param("example") ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int updateByExample(@Param("record") Apply record, @Param("example") ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Apply
     *
     * @mbggenerated Tue Sep 19 09:42:01 CST 2017
     */
    int updateByPrimaryKey(Apply record);
    
    public List<ApplyWithEval>selectApplyWithEval(@Param("userId") String userId, @Param("status") String status);
    
    public ApplyWithEval selectApplyWithEvalByEFId(@Param("efId") String efId);
    
    /**
     * 查询该人员、该序列 本年 提交的条数  
     * @param record
     * @return
     */
    int getCount(@Param("userId") String userId,@Param("seq")String seq,@Param("year") String year,@Param("status")String status);
}