package com.dynastech.model.mapper;

import com.dynastech.model.entity.PersonEvaluationform;
import com.dynastech.model.entity.PersonEvaluationformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonEvaluationformMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int countByExample(PersonEvaluationformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int deleteByExample(PersonEvaluationformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int insert(PersonEvaluationform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int insertSelective(PersonEvaluationform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	List<PersonEvaluationform> selectByExample(PersonEvaluationformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	PersonEvaluationform selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PersonEvaluationform record,
			@Param("example") PersonEvaluationformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int updateByExample(@Param("record") PersonEvaluationform record,
			@Param("example") PersonEvaluationformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int updateByPrimaryKeySelective(PersonEvaluationform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_evaluationform
	 * @mbggenerated  Sat Sep 30 15:19:15 CST 2017
	 */
	int updateByPrimaryKey(PersonEvaluationform record);
}