package com.dynastech.model.mapper;

import com.dynastech.model.entity.PersonAbilityEvaluate;
import com.dynastech.model.entity.PersonAbilityEvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonAbilityEvaluateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int countByExample(PersonAbilityEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int deleteByExample(PersonAbilityEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int insert(PersonAbilityEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int insertSelective(PersonAbilityEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	List<PersonAbilityEvaluate> selectByExample(PersonAbilityEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	PersonAbilityEvaluate selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PersonAbilityEvaluate record,
			@Param("example") PersonAbilityEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int updateByExample(@Param("record") PersonAbilityEvaluate record,
			@Param("example") PersonAbilityEvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int updateByPrimaryKeySelective(PersonAbilityEvaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	int updateByPrimaryKey(PersonAbilityEvaluate record);
}