package com.dynastech.model.mapper;

import com.dynastech.model.entity.SysAbility;
import com.dynastech.model.entity.SysAbilityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysAbilityMapper {

    List<Map<String, String>> getSysAbilityItem();


    int countByEvaluationId(@Param("evaluationId") String evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int countByExample(SysAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int deleteByExample(SysAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int insert(SysAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int insertSelective(SysAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    List<SysAbility> selectByExample(SysAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    SysAbility selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysAbility record, @Param("example") SysAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int updateByExample(@Param("record") SysAbility record, @Param("example") SysAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int updateByPrimaryKeySelective(SysAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ability
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    int updateByPrimaryKey(SysAbility record);
}