package com.dynastech.model.mapper;

import com.dynastech.model.entity.SysEvaluationFormAbility;
import com.dynastech.model.entity.SysEvaluationFormAbilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysEvaluationFormAbilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int countByExample(SysEvaluationFormAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int deleteByExample(SysEvaluationFormAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int insert(SysEvaluationFormAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int insertSelective(SysEvaluationFormAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    List<SysEvaluationFormAbility> selectByExample(SysEvaluationFormAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    SysEvaluationFormAbility selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysEvaluationFormAbility record, @Param("example") SysEvaluationFormAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int updateByExample(@Param("record") SysEvaluationFormAbility record, @Param("example") SysEvaluationFormAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int updateByPrimaryKeySelective(SysEvaluationFormAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    int updateByPrimaryKey(SysEvaluationFormAbility record);
}