package com.dynastech.model.mapper;

import com.dynastech.model.entity.SysEvaluationForm;
import com.dynastech.model.entity.SysEvaluationFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysEvaluationFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int countByExample(SysEvaluationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int deleteByExample(SysEvaluationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int insert(SysEvaluationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int insertSelective(SysEvaluationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    List<SysEvaluationForm> selectByExample(SysEvaluationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    SysEvaluationForm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysEvaluationForm record, @Param("example") SysEvaluationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int updateByExample(@Param("record") SysEvaluationForm record, @Param("example") SysEvaluationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int updateByPrimaryKeySelective(SysEvaluationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    int updateByPrimaryKey(SysEvaluationForm record);
}