package com.dynastech.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.OrganizationUser;
import com.dynastech.system.entity.OrganizationUserExample;
import com.dynastech.system.entity.OrganizationUserKey;

public interface OrganizationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int countByExample(OrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int deleteByExample(OrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int deleteByPrimaryKey(OrganizationUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int insert(OrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int insertSelective(OrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    List<OrganizationUser> selectByExample(OrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    OrganizationUser selectByPrimaryKey(OrganizationUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrganizationUser record, @Param("example") OrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int updateByExample(@Param("record") OrganizationUser record, @Param("example") OrganizationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int updateByPrimaryKeySelective(OrganizationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationUser
     *
     * @mbggenerated Wed Aug 16 15:44:37 CST 2017
     */
    int updateByPrimaryKey(OrganizationUser record);
}