package com.dynastech.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.OrganizationDepth;
import com.dynastech.system.entity.OrganizationDepthExample;
import com.dynastech.system.entity.OrganizationDepthKey;

public interface OrganizationDepthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int countByExample(OrganizationDepthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int deleteByExample(OrganizationDepthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int deleteByPrimaryKey(OrganizationDepthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int insert(OrganizationDepth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int insertSelective(OrganizationDepth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    List<OrganizationDepth> selectByExample(OrganizationDepthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    OrganizationDepth selectByPrimaryKey(OrganizationDepthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrganizationDepth record, @Param("example") OrganizationDepthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int updateByExample(@Param("record") OrganizationDepth record, @Param("example") OrganizationDepthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int updateByPrimaryKeySelective(OrganizationDepth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_OrganizationDepth
     *
     * @mbggenerated Wed Jul 26 17:45:19 CST 2017
     */
    int updateByPrimaryKey(OrganizationDepth record);
}