package com.dynastech.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.Resource;
import com.dynastech.system.entity.ResourceExample;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_resource
     *
     * @mbggenerated Fri Aug 11 10:05:57 CST 2017
     */
    int updateByPrimaryKey(Resource record);
    
    /**
     * 查询所有菜单 先不判定权限
     * @return
     */
    List<Resource> findMenus(ResourceExample example);
    
    
    List<Resource> findResourceByUserId(@Param("userId")String userId,@Param("type")String type);
}