package com.dynastech.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.RoleType;
import com.dynastech.system.entity.RoleTypeExample;

public interface RoleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int countByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int deleteByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int insert(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int insertSelective(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    List<RoleType> selectByExample(RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    RoleType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleType record, @Param("example") RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int updateByExample(@Param("record") RoleType record, @Param("example") RoleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int updateByPrimaryKeySelective(RoleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_RoleType
     *
     * @mbggenerated Mon Aug 14 16:41:32 CST 2017
     */
    int updateByPrimaryKey(RoleType record);
}