package com.dynastech.system.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.UserSerial;
import com.dynastech.system.entity.UserSerialExample;

public interface UserSerialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int countByExample(UserSerialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int deleteByExample(UserSerialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int insert(UserSerial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int insertSelective(UserSerial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	List<UserSerial> selectByExample(UserSerialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	UserSerial selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserSerial record, @Param("example") UserSerialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int updateByExample(@Param("record") UserSerial record, @Param("example") UserSerialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int updateByPrimaryKeySelective(UserSerial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rs_user_Serial
	 * @mbggenerated  Fri Nov 24 18:05:56 CST 2017
	 */
	int updateByPrimaryKey(UserSerial record);
	
	List<UserSerial> selectSerialUserById(@Param("sid")String sid,@Param("type")String type);
	
	List<Map<String,String>> userListForSelect2(@Param("sid")String sid);
}