package com.dynastech.flow.mapper;

import com.dynastech.flow.entity.Identitylink;
import com.dynastech.flow.entity.IdentitylinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdentitylinkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int countByExample(IdentitylinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int deleteByExample(IdentitylinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int insert(Identitylink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int insertSelective(Identitylink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	List<Identitylink> selectByExample(IdentitylinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	Identitylink selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Identitylink record, @Param("example") IdentitylinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int updateByExample(@Param("record") Identitylink record, @Param("example") IdentitylinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int updateByPrimaryKeySelective(Identitylink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_identitylink
	 * @mbggenerated  Tue Dec 05 15:11:47 CST 2017
	 */
	int updateByPrimaryKey(Identitylink record);
}