package com.dynastech.flow.mapper;

import com.dynastech.flow.entity.QueryTask;
import com.dynastech.flow.entity.Task;
import com.dynastech.flow.entity.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int countByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int deleteByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int insert(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	List<Task> selectByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	Task selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int updateByPrimaryKeySelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table F_TASK
	 * @mbggenerated  Tue Nov 07 15:27:22 CST 2017
	 */
	int updateByPrimaryKey(Task record);

	List<Task> selectTask(
			@Param("roles") List<String> roles,
			@Param("userId")String userId,
			@Param("queryTask")QueryTask queryTask);
}