package com.dynastech.common.mapper;

import com.dynastech.common.entity.Dictionary;
import com.dynastech.common.entity.DictionaryExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int countByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int deleteByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    List<Dictionary> selectByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    Dictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int updateByExample(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_Dictionary
     *
     * @mbggenerated Mon Aug 28 09:05:49 CST 2017
     */
    int updateByPrimaryKey(Dictionary record);

    List<Map<String,Object>> getDicKind();
}