package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.List;

public class AttachmentFileRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public AttachmentFileRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("afr.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("afr.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("afr.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("afr.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("afr.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("afr.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("afr.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("afr.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("afr.id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("afr.id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("afr.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("afr.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("afr.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("afr.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYwidIsNull() {
            addCriterion("afr.ywId is null");
            return (Criteria) this;
        }

        public Criteria andYwidIsNotNull() {
            addCriterion("afr.ywId is not null");
            return (Criteria) this;
        }

        public Criteria andYwidEqualTo(String value) {
            addCriterion("afr.ywId =", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidNotEqualTo(String value) {
            addCriterion("afr.ywId <>", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidGreaterThan(String value) {
            addCriterion("afr.ywId >", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidGreaterThanOrEqualTo(String value) {
            addCriterion("afr.ywId >=", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidLessThan(String value) {
            addCriterion("afr.ywId <", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidLessThanOrEqualTo(String value) {
            addCriterion("afr.ywId <=", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidLike(String value) {
            addCriterion("afr.ywId like", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidNotLike(String value) {
            addCriterion("afr.ywId not like", value, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidIn(List<String> values) {
            addCriterion("afr.ywId in", values, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidNotIn(List<String> values) {
            addCriterion("afr.ywId not in", values, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidBetween(String value1, String value2) {
            addCriterion("afr.ywId between", value1, value2, "ywid");
            return (Criteria) this;
        }

        public Criteria andYwidNotBetween(String value1, String value2) {
            addCriterion("afr.ywId not between", value1, value2, "ywid");
            return (Criteria) this;
        }

        public Criteria andFileidIsNull() {
            addCriterion("afr.fileId is null");
            return (Criteria) this;
        }

        public Criteria andFileidIsNotNull() {
            addCriterion("afr.fileId is not null");
            return (Criteria) this;
        }

        public Criteria andFileidEqualTo(String value) {
            addCriterion("afr.fileId =", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotEqualTo(String value) {
            addCriterion("afr.fileId <>", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThan(String value) {
            addCriterion("afr.fileId >", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidGreaterThanOrEqualTo(String value) {
            addCriterion("afr.fileId >=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThan(String value) {
            addCriterion("afr.fileId <", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLessThanOrEqualTo(String value) {
            addCriterion("afr.fileId <=", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidLike(String value) {
            addCriterion("afr.fileId like", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotLike(String value) {
            addCriterion("afr.fileId not like", value, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidIn(List<String> values) {
            addCriterion("afr.fileId in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotIn(List<String> values) {
            addCriterion("afr.fileId not in", values, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidBetween(String value1, String value2) {
            addCriterion("afr.fileId between", value1, value2, "fileid");
            return (Criteria) this;
        }

        public Criteria andFileidNotBetween(String value1, String value2) {
            addCriterion("afr.fileId not between", value1, value2, "fileid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 29 10:00:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_Attachment_File_relation
     *
     * @mbggenerated Fri Sep 29 10:00:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}