package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExamExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public ExamExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("e.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("e.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("e.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("e.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("e.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("e.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("e.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("e.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("e.id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("e.id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("e.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("e.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("e.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("e.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("e.username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("e.username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("e.username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("e.username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("e.username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("e.username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("e.username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("e.username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("e.username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("e.username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("e.username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("e.username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("e.username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("e.username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andKindIsNull() {
			addCriterion("e.kind is null");
			return (Criteria) this;
		}

		public Criteria andKindIsNotNull() {
			addCriterion("e.kind is not null");
			return (Criteria) this;
		}

		public Criteria andKindEqualTo(String value) {
			addCriterion("e.kind =", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotEqualTo(String value) {
			addCriterion("e.kind <>", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindGreaterThan(String value) {
			addCriterion("e.kind >", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindGreaterThanOrEqualTo(String value) {
			addCriterion("e.kind >=", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindLessThan(String value) {
			addCriterion("e.kind <", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindLessThanOrEqualTo(String value) {
			addCriterion("e.kind <=", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindLike(String value) {
			addCriterion("e.kind like", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotLike(String value) {
			addCriterion("e.kind not like", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindIn(List<String> values) {
			addCriterion("e.kind in", values, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotIn(List<String> values) {
			addCriterion("e.kind not in", values, "kind");
			return (Criteria) this;
		}

		public Criteria andKindBetween(String value1, String value2) {
			addCriterion("e.kind between", value1, value2, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotBetween(String value1, String value2) {
			addCriterion("e.kind not between", value1, value2, "kind");
			return (Criteria) this;
		}

		public Criteria andDateIsNull() {
			addCriterion("e.date is null");
			return (Criteria) this;
		}

		public Criteria andDateIsNotNull() {
			addCriterion("e.date is not null");
			return (Criteria) this;
		}

		public Criteria andDateEqualTo(String value) {
			addCriterion("e.date =", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotEqualTo(String value) {
			addCriterion("e.date <>", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThan(String value) {
			addCriterion("e.date >", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThanOrEqualTo(String value) {
			addCriterion("e.date >=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThan(String value) {
			addCriterion("e.date <", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThanOrEqualTo(String value) {
			addCriterion("e.date <=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLike(String value) {
			addCriterion("e.date like", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotLike(String value) {
			addCriterion("e.date not like", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateIn(List<String> values) {
			addCriterion("e.date in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotIn(List<String> values) {
			addCriterion("e.date not in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateBetween(String value1, String value2) {
			addCriterion("e.date between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotBetween(String value1, String value2) {
			addCriterion("e.date not between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("e.score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("e.score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(String value) {
			addCriterion("e.score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(String value) {
			addCriterion("e.score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(String value) {
			addCriterion("e.score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(String value) {
			addCriterion("e.score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(String value) {
			addCriterion("e.score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(String value) {
			addCriterion("e.score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLike(String value) {
			addCriterion("e.score like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotLike(String value) {
			addCriterion("e.score not like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<String> values) {
			addCriterion("e.score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<String> values) {
			addCriterion("e.score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(String value1, String value2) {
			addCriterion("e.score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(String value1, String value2) {
			addCriterion("e.score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNull() {
			addCriterion("e.DateTimeCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNotNull() {
			addCriterion("e.DateTimeCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedEqualTo(Date value) {
			addCriterion("e.DateTimeCreated =", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotEqualTo(Date value) {
			addCriterion("e.DateTimeCreated <>", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThan(Date value) {
			addCriterion("e.DateTimeCreated >", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("e.DateTimeCreated >=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThan(Date value) {
			addCriterion("e.DateTimeCreated <", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
			addCriterion("e.DateTimeCreated <=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIn(List<Date> values) {
			addCriterion("e.DateTimeCreated in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotIn(List<Date> values) {
			addCriterion("e.DateTimeCreated not in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
			addCriterion("e.DateTimeCreated between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
			addCriterion("e.DateTimeCreated not between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNull() {
			addCriterion("e.DateTimeModified is null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNotNull() {
			addCriterion("e.DateTimeModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedEqualTo(Date value) {
			addCriterion("e.DateTimeModified =", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotEqualTo(Date value) {
			addCriterion("e.DateTimeModified <>", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThan(Date value) {
			addCriterion("e.DateTimeModified >", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("e.DateTimeModified >=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThan(Date value) {
			addCriterion("e.DateTimeModified <", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("e.DateTimeModified <=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIn(List<Date> values) {
			addCriterion("e.DateTimeModified in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotIn(List<Date> values) {
			addCriterion("e.DateTimeModified not in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
			addCriterion("e.DateTimeModified between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("e.DateTimeModified not between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("e.isDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("e.isDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("e.isDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("e.isDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("e.isDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("e.isDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("e.isDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("e.isDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("e.isDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("e.isDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("e.isDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("e.isDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andSeqIsNull() {
			addCriterion("e.seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("e.seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(String value) {
			addCriterion("e.seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(String value) {
			addCriterion("e.seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(String value) {
			addCriterion("e.seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(String value) {
			addCriterion("e.seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(String value) {
			addCriterion("e.seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(String value) {
			addCriterion("e.seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLike(String value) {
			addCriterion("e.seq like", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotLike(String value) {
			addCriterion("e.seq not like", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<String> values) {
			addCriterion("e.seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<String> values) {
			addCriterion("e.seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(String value1, String value2) {
			addCriterion("e.seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(String value1, String value2) {
			addCriterion("e.seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("e.level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("e.level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(String value) {
			addCriterion("e.level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(String value) {
			addCriterion("e.level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(String value) {
			addCriterion("e.level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(String value) {
			addCriterion("e.level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(String value) {
			addCriterion("e.level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(String value) {
			addCriterion("e.level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLike(String value) {
			addCriterion("e.level like", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotLike(String value) {
			addCriterion("e.level not like", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<String> values) {
			addCriterion("e.level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<String> values) {
			addCriterion("e.level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(String value1, String value2) {
			addCriterion("e.level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(String value1, String value2) {
			addCriterion("e.level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("e.userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("e.userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("e.userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("e.userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("e.userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("e.userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("e.userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("e.userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("e.userId like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("e.userId not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("e.userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("e.userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("e.userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("e.userId not between", value1, value2, "userid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_exam
	 * @mbggenerated  Thu Nov 30 16:50:09 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 19 17:54:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}