package com.dynastech.model.entity;

public class MarkSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_markSetting.id
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_markSetting.level
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_markSetting.id
     *
     * @return the value of t_markSetting.id
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_markSetting.id
     *
     * @param id the value for t_markSetting.id
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_markSetting.level
     *
     * @return the value of t_markSetting.level
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_markSetting.level
     *
     * @param level the value for t_markSetting.level
     *
     * @mbggenerated Tue Oct 24 15:35:57 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}