package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonAbilityEvaluateExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public PersonAbilityEvaluateExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("pae.ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("pae.ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("pae.ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("pae.ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("pae.ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("pae.ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("pae.ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("pae.ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("pae.ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("pae.ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("pae.ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("pae.ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("pae.ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("pae.ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAbilityidIsNull() {
			addCriterion("pae.abilityId is null");
			return (Criteria) this;
		}

		public Criteria andAbilityidIsNotNull() {
			addCriterion("pae.abilityId is not null");
			return (Criteria) this;
		}

		public Criteria andAbilityidEqualTo(String value) {
			addCriterion("pae.abilityId =", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidNotEqualTo(String value) {
			addCriterion("pae.abilityId <>", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidGreaterThan(String value) {
			addCriterion("pae.abilityId >", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidGreaterThanOrEqualTo(String value) {
			addCriterion("pae.abilityId >=", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidLessThan(String value) {
			addCriterion("pae.abilityId <", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidLessThanOrEqualTo(String value) {
			addCriterion("pae.abilityId <=", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidLike(String value) {
			addCriterion("pae.abilityId like", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidNotLike(String value) {
			addCriterion("pae.abilityId not like", value, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidIn(List<String> values) {
			addCriterion("pae.abilityId in", values, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidNotIn(List<String> values) {
			addCriterion("pae.abilityId not in", values, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidBetween(String value1, String value2) {
			addCriterion("pae.abilityId between", value1, value2, "abilityid");
			return (Criteria) this;
		}

		public Criteria andAbilityidNotBetween(String value1, String value2) {
			addCriterion("pae.abilityId not between", value1, value2, "abilityid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidIsNull() {
			addCriterion("pae.evaluationformId is null");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidIsNotNull() {
			addCriterion("pae.evaluationformId is not null");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidEqualTo(String value) {
			addCriterion("pae.evaluationformId =", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidNotEqualTo(String value) {
			addCriterion("pae.evaluationformId <>", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidGreaterThan(String value) {
			addCriterion("pae.evaluationformId >", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidGreaterThanOrEqualTo(String value) {
			addCriterion("pae.evaluationformId >=", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidLessThan(String value) {
			addCriterion("pae.evaluationformId <", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidLessThanOrEqualTo(String value) {
			addCriterion("pae.evaluationformId <=", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidLike(String value) {
			addCriterion("pae.evaluationformId like", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidNotLike(String value) {
			addCriterion("pae.evaluationformId not like", value, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidIn(List<String> values) {
			addCriterion("pae.evaluationformId in", values, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidNotIn(List<String> values) {
			addCriterion("pae.evaluationformId not in", values, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidBetween(String value1, String value2) {
			addCriterion("pae.evaluationformId between", value1, value2, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andEvaluationformidNotBetween(String value1, String value2) {
			addCriterion("pae.evaluationformId not between", value1, value2, "evaluationformid");
			return (Criteria) this;
		}

		public Criteria andAssessoridIsNull() {
			addCriterion("pae.assessorId is null");
			return (Criteria) this;
		}

		public Criteria andAssessoridIsNotNull() {
			addCriterion("pae.assessorId is not null");
			return (Criteria) this;
		}

		public Criteria andAssessoridEqualTo(String value) {
			addCriterion("pae.assessorId =", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridNotEqualTo(String value) {
			addCriterion("pae.assessorId <>", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridGreaterThan(String value) {
			addCriterion("pae.assessorId >", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridGreaterThanOrEqualTo(String value) {
			addCriterion("pae.assessorId >=", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridLessThan(String value) {
			addCriterion("pae.assessorId <", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridLessThanOrEqualTo(String value) {
			addCriterion("pae.assessorId <=", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridLike(String value) {
			addCriterion("pae.assessorId like", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridNotLike(String value) {
			addCriterion("pae.assessorId not like", value, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridIn(List<String> values) {
			addCriterion("pae.assessorId in", values, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridNotIn(List<String> values) {
			addCriterion("pae.assessorId not in", values, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridBetween(String value1, String value2) {
			addCriterion("pae.assessorId between", value1, value2, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessoridNotBetween(String value1, String value2) {
			addCriterion("pae.assessorId not between", value1, value2, "assessorid");
			return (Criteria) this;
		}

		public Criteria andAssessorIsNull() {
			addCriterion("pae.assessor is null");
			return (Criteria) this;
		}

		public Criteria andAssessorIsNotNull() {
			addCriterion("pae.assessor is not null");
			return (Criteria) this;
		}

		public Criteria andAssessorEqualTo(String value) {
			addCriterion("pae.assessor =", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorNotEqualTo(String value) {
			addCriterion("pae.assessor <>", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorGreaterThan(String value) {
			addCriterion("pae.assessor >", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorGreaterThanOrEqualTo(String value) {
			addCriterion("pae.assessor >=", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorLessThan(String value) {
			addCriterion("pae.assessor <", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorLessThanOrEqualTo(String value) {
			addCriterion("pae.assessor <=", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorLike(String value) {
			addCriterion("pae.assessor like", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorNotLike(String value) {
			addCriterion("pae.assessor not like", value, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorIn(List<String> values) {
			addCriterion("pae.assessor in", values, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorNotIn(List<String> values) {
			addCriterion("pae.assessor not in", values, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorBetween(String value1, String value2) {
			addCriterion("pae.assessor between", value1, value2, "assessor");
			return (Criteria) this;
		}

		public Criteria andAssessorNotBetween(String value1, String value2) {
			addCriterion("pae.assessor not between", value1, value2, "assessor");
			return (Criteria) this;
		}

		public Criteria andScoringIsNull() {
			addCriterion("pae.scoring is null");
			return (Criteria) this;
		}

		public Criteria andScoringIsNotNull() {
			addCriterion("pae.scoring is not null");
			return (Criteria) this;
		}

		public Criteria andScoringEqualTo(Double value) {
			addCriterion("pae.scoring =", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringNotEqualTo(Double value) {
			addCriterion("pae.scoring <>", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringGreaterThan(Double value) {
			addCriterion("pae.scoring >", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringGreaterThanOrEqualTo(Double value) {
			addCriterion("pae.scoring >=", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringLessThan(Double value) {
			addCriterion("pae.scoring <", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringLessThanOrEqualTo(Double value) {
			addCriterion("pae.scoring <=", value, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringIn(List<Double> values) {
			addCriterion("pae.scoring in", values, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringNotIn(List<Double> values) {
			addCriterion("pae.scoring not in", values, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringBetween(Double value1, Double value2) {
			addCriterion("pae.scoring between", value1, value2, "scoring");
			return (Criteria) this;
		}

		public Criteria andScoringNotBetween(Double value1, Double value2) {
			addCriterion("pae.scoring not between", value1, value2, "scoring");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNull() {
			addCriterion("pae.DateTimeCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNotNull() {
			addCriterion("pae.DateTimeCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedEqualTo(Date value) {
			addCriterion("pae.DateTimeCreated =", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotEqualTo(Date value) {
			addCriterion("pae.DateTimeCreated <>", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThan(Date value) {
			addCriterion("pae.DateTimeCreated >", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("pae.DateTimeCreated >=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThan(Date value) {
			addCriterion("pae.DateTimeCreated <", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
			addCriterion("pae.DateTimeCreated <=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIn(List<Date> values) {
			addCriterion("pae.DateTimeCreated in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotIn(List<Date> values) {
			addCriterion("pae.DateTimeCreated not in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
			addCriterion("pae.DateTimeCreated between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
			addCriterion("pae.DateTimeCreated not between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNull() {
			addCriterion("pae.DateTimeModified is null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNotNull() {
			addCriterion("pae.DateTimeModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedEqualTo(Date value) {
			addCriterion("pae.DateTimeModified =", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotEqualTo(Date value) {
			addCriterion("pae.DateTimeModified <>", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThan(Date value) {
			addCriterion("pae.DateTimeModified >", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("pae.DateTimeModified >=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThan(Date value) {
			addCriterion("pae.DateTimeModified <", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("pae.DateTimeModified <=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIn(List<Date> values) {
			addCriterion("pae.DateTimeModified in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotIn(List<Date> values) {
			addCriterion("pae.DateTimeModified not in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
			addCriterion("pae.DateTimeModified between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("pae.DateTimeModified not between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("pae.isDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("pae.isDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("pae.isDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("pae.isDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("pae.isDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("pae.isDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("pae.isDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("pae.isDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("pae.isDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("pae.isDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("pae.isDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("pae.isDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("pae.note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("pae.note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("pae.note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("pae.note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("pae.note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("pae.note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("pae.note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("pae.note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("pae.note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("pae.note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("pae.note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("pae.note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("pae.note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("pae.note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andAbilitynameIsNull() {
			addCriterion("pae.abilityName is null");
			return (Criteria) this;
		}

		public Criteria andAbilitynameIsNotNull() {
			addCriterion("pae.abilityName is not null");
			return (Criteria) this;
		}

		public Criteria andAbilitynameEqualTo(String value) {
			addCriterion("pae.abilityName =", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameNotEqualTo(String value) {
			addCriterion("pae.abilityName <>", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameGreaterThan(String value) {
			addCriterion("pae.abilityName >", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameGreaterThanOrEqualTo(String value) {
			addCriterion("pae.abilityName >=", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameLessThan(String value) {
			addCriterion("pae.abilityName <", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameLessThanOrEqualTo(String value) {
			addCriterion("pae.abilityName <=", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameLike(String value) {
			addCriterion("pae.abilityName like", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameNotLike(String value) {
			addCriterion("pae.abilityName not like", value, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameIn(List<String> values) {
			addCriterion("pae.abilityName in", values, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameNotIn(List<String> values) {
			addCriterion("pae.abilityName not in", values, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameBetween(String value1, String value2) {
			addCriterion("pae.abilityName between", value1, value2, "abilityname");
			return (Criteria) this;
		}

		public Criteria andAbilitynameNotBetween(String value1, String value2) {
			addCriterion("pae.abilityName not between", value1, value2, "abilityname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_ability_evaluate
	 * @mbggenerated  Thu Nov 09 15:06:04 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ability_evaluate
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 24 09:51:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}