package com.dynastech.model.entity;

import java.util.Date;

public class Plan {

    private  String cnSerial;

    public String getCnSerial() {
        return cnSerial;
    }

    public void setCnSerial(String cnSerial) {
        this.cnSerial = cnSerial;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.id
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.name
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.type
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.serial
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.level
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.sYear
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private Integer syear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.status
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.starttime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.endtime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.DateTimeCreated
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private Date datetimecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.DateTimeModified
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private Date datetimemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.isDeleted
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    private Boolean isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.id
     *
     * @return the value of t_plan.id
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.id
     *
     * @param id the value for t_plan.id
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.name
     *
     * @return the value of t_plan.name
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.name
     *
     * @param name the value for t_plan.name
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.type
     *
     * @return the value of t_plan.type
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.type
     *
     * @param type the value for t_plan.type
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.serial
     *
     * @return the value of t_plan.serial
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.serial
     *
     * @param serial the value for t_plan.serial
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.level
     *
     * @return the value of t_plan.level
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.level
     *
     * @param level the value for t_plan.level
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.sYear
     *
     * @return the value of t_plan.sYear
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public Integer getSyear() {
        return syear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.sYear
     *
     * @param syear the value for t_plan.sYear
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setSyear(Integer syear) {
        this.syear = syear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.status
     *
     * @return the value of t_plan.status
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.status
     *
     * @param status the value for t_plan.status
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.starttime
     *
     * @return the value of t_plan.starttime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.starttime
     *
     * @param starttime the value for t_plan.starttime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.endtime
     *
     * @return the value of t_plan.endtime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.endtime
     *
     * @param endtime the value for t_plan.endtime
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.DateTimeCreated
     *
     * @return the value of t_plan.DateTimeCreated
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public Date getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.DateTimeCreated
     *
     * @param datetimecreated the value for t_plan.DateTimeCreated
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setDatetimecreated(Date datetimecreated) {
        this.datetimecreated = datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.DateTimeModified
     *
     * @return the value of t_plan.DateTimeModified
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public Date getDatetimemodified() {
        return datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.DateTimeModified
     *
     * @param datetimemodified the value for t_plan.DateTimeModified
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setDatetimemodified(Date datetimemodified) {
        this.datetimemodified = datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.isDeleted
     *
     * @return the value of t_plan.isDeleted
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.isDeleted
     *
     * @param isdeleted the value for t_plan.isDeleted
     *
     * @mbggenerated Tue Oct 17 10:50:37 CST 2017
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
}