package com.dynastech.model.entity;

import java.util.Date;

public class SysAbility {


    private String cnSerial;
    private String cnTheLevel;


    public String getCnSerial() {
        return cnSerial;
    }

    public void setCnSerial(String cnSerial) {
        this.cnSerial = cnSerial;
    }

    public String getCnTheLevel() {
        return cnTheLevel;
    }

    public void setCnTheLevel(String cnTheLevel) {
        this.cnTheLevel = cnTheLevel;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.ID
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.name
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.typeId
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String typeid;
    
    private String typeV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.Serial
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.TheLevel
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String thelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.evidence
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String evidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.Score
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.formula
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private String formula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.passmark
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private Double passmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private Date datetimecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private Date datetimemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ability.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    private Boolean isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.ID
     *
     * @return the value of sys_ability.ID
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.ID
     *
     * @param id the value for sys_ability.ID
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.name
     *
     * @return the value of sys_ability.name
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.name
     *
     * @param name the value for sys_ability.name
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.typeId
     *
     * @return the value of sys_ability.typeId
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.typeId
     *
     * @param typeid the value for sys_ability.typeId
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.Serial
     *
     * @return the value of sys_ability.Serial
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.Serial
     *
     * @param serial the value for sys_ability.Serial
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.TheLevel
     *
     * @return the value of sys_ability.TheLevel
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getThelevel() {
        return thelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.TheLevel
     *
     * @param thelevel the value for sys_ability.TheLevel
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setThelevel(String thelevel) {
        this.thelevel = thelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.evidence
     *
     * @return the value of sys_ability.evidence
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getEvidence() {
        return evidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.evidence
     *
     * @param evidence the value for sys_ability.evidence
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.Score
     *
     * @return the value of sys_ability.Score
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.Score
     *
     * @param score the value for sys_ability.Score
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.formula
     *
     * @return the value of sys_ability.formula
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.formula
     *
     * @param formula the value for sys_ability.formula
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setFormula(String formula) {
        this.formula = formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.passmark
     *
     * @return the value of sys_ability.passmark
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public Double getPassmark() {
        return passmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.passmark
     *
     * @param passmark the value for sys_ability.passmark
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setPassmark(Double passmark) {
        this.passmark = passmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.DateTimeCreated
     *
     * @return the value of sys_ability.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public Date getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.DateTimeCreated
     *
     * @param datetimecreated the value for sys_ability.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setDatetimecreated(Date datetimecreated) {
        this.datetimecreated = datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.DateTimeModified
     *
     * @return the value of sys_ability.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public Date getDatetimemodified() {
        return datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.DateTimeModified
     *
     * @param datetimemodified the value for sys_ability.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setDatetimemodified(Date datetimemodified) {
        this.datetimemodified = datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ability.isDeleted
     *
     * @return the value of sys_ability.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ability.isDeleted
     *
     * @param isdeleted the value for sys_ability.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:38:30 CST 2017
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
    
    public String getTypeV() {
		return typeV;
	}
    
    public void setTypeV(String typeV) {
		this.typeV = typeV;
	}
}