package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.List;

public class SysEvaluationFormAbilityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public SysEvaluationFormAbilityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("sea.ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("sea.ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("sea.ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("sea.ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("sea.ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("sea.ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("sea.ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("sea.ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("sea.ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("sea.ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("sea.ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("sea.ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("sea.ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("sea.ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidIsNull() {
            addCriterion("sea.evaluationformId is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidIsNotNull() {
            addCriterion("sea.evaluationformId is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidEqualTo(String value) {
            addCriterion("sea.evaluationformId =", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidNotEqualTo(String value) {
            addCriterion("sea.evaluationformId <>", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidGreaterThan(String value) {
            addCriterion("sea.evaluationformId >", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidGreaterThanOrEqualTo(String value) {
            addCriterion("sea.evaluationformId >=", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidLessThan(String value) {
            addCriterion("sea.evaluationformId <", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidLessThanOrEqualTo(String value) {
            addCriterion("sea.evaluationformId <=", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidLike(String value) {
            addCriterion("sea.evaluationformId like", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidNotLike(String value) {
            addCriterion("sea.evaluationformId not like", value, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidIn(List<String> values) {
            addCriterion("sea.evaluationformId in", values, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidNotIn(List<String> values) {
            addCriterion("sea.evaluationformId not in", values, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidBetween(String value1, String value2) {
            addCriterion("sea.evaluationformId between", value1, value2, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andEvaluationformidNotBetween(String value1, String value2) {
            addCriterion("sea.evaluationformId not between", value1, value2, "evaluationformid");
            return (Criteria) this;
        }

        public Criteria andAbilityidIsNull() {
            addCriterion("sea.abilityId is null");
            return (Criteria) this;
        }

        public Criteria andAbilityidIsNotNull() {
            addCriterion("sea.abilityId is not null");
            return (Criteria) this;
        }

        public Criteria andAbilityidEqualTo(String value) {
            addCriterion("sea.abilityId =", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidNotEqualTo(String value) {
            addCriterion("sea.abilityId <>", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidGreaterThan(String value) {
            addCriterion("sea.abilityId >", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidGreaterThanOrEqualTo(String value) {
            addCriterion("sea.abilityId >=", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidLessThan(String value) {
            addCriterion("sea.abilityId <", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidLessThanOrEqualTo(String value) {
            addCriterion("sea.abilityId <=", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidLike(String value) {
            addCriterion("sea.abilityId like", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidNotLike(String value) {
            addCriterion("sea.abilityId not like", value, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidIn(List<String> values) {
            addCriterion("sea.abilityId in", values, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidNotIn(List<String> values) {
            addCriterion("sea.abilityId not in", values, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidBetween(String value1, String value2) {
            addCriterion("sea.abilityId between", value1, value2, "abilityid");
            return (Criteria) this;
        }

        public Criteria andAbilityidNotBetween(String value1, String value2) {
            addCriterion("sea.abilityId not between", value1, value2, "abilityid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 18 13:39:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform_ability
     *
     * @mbggenerated Mon Sep 18 13:39:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}