package com.dynastech.model.entity;

import java.util.Date;

public class SysEvaluationForm {
	
	
	public static final String STUTUS_0="草稿";
	public static final String STUTUS_1="已发布";
	public static final String STUTUS_2="已作废";

	public  String cnSerial;
	public  String cnLevel;

    public String getCnSerial() {
        return cnSerial;
    }

    public void setCnSerial(String cnSerial) {
        this.cnSerial = cnSerial;
    }

    public String getCnLevel() {
        return cnLevel;
    }

    public void setCnLevel(String cnLevel) {
        this.cnLevel = cnLevel;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.ID
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.name
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.Serial
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.level
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.version
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.status
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String status=STUTUS_0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.total
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.passmark
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Double passmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.judgesNumber
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Integer judgesnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Date datetimecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Date datetimemodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private Boolean isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_evaluationform.standardFile
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    private String standardfile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.ID
     *
     * @return the value of sys_evaluationform.ID
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.ID
     *
     * @param id the value for sys_evaluationform.ID
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.name
     *
     * @return the value of sys_evaluationform.name
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.name
     *
     * @param name the value for sys_evaluationform.name
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.Serial
     *
     * @return the value of sys_evaluationform.Serial
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.Serial
     *
     * @param serial the value for sys_evaluationform.Serial
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.level
     *
     * @return the value of sys_evaluationform.level
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.level
     *
     * @param level the value for sys_evaluationform.level
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.version
     *
     * @return the value of sys_evaluationform.version
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.version
     *
     * @param version the value for sys_evaluationform.version
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.status
     *
     * @return the value of sys_evaluationform.status
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.status
     *
     * @param status the value for sys_evaluationform.status
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.total
     *
     * @return the value of sys_evaluationform.total
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.total
     *
     * @param total the value for sys_evaluationform.total
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.passmark
     *
     * @return the value of sys_evaluationform.passmark
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Double getPassmark() {
        return passmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.passmark
     *
     * @param passmark the value for sys_evaluationform.passmark
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setPassmark(Double passmark) {
        this.passmark = passmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.judgesNumber
     *
     * @return the value of sys_evaluationform.judgesNumber
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Integer getJudgesnumber() {
        return judgesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.judgesNumber
     *
     * @param judgesnumber the value for sys_evaluationform.judgesNumber
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setJudgesnumber(Integer judgesnumber) {
        this.judgesnumber = judgesnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.DateTimeCreated
     *
     * @return the value of sys_evaluationform.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Date getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.DateTimeCreated
     *
     * @param datetimecreated the value for sys_evaluationform.DateTimeCreated
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setDatetimecreated(Date datetimecreated) {
        this.datetimecreated = datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.DateTimeModified
     *
     * @return the value of sys_evaluationform.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Date getDatetimemodified() {
        return datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.DateTimeModified
     *
     * @param datetimemodified the value for sys_evaluationform.DateTimeModified
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setDatetimemodified(Date datetimemodified) {
        this.datetimemodified = datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.isDeleted
     *
     * @return the value of sys_evaluationform.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.isDeleted
     *
     * @param isdeleted the value for sys_evaluationform.isDeleted
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_evaluationform.standardFile
     *
     * @return the value of sys_evaluationform.standardFile
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getStandardfile() {
        return standardfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_evaluationform.standardFile
     *
     * @param standardfile the value for sys_evaluationform.standardFile
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setStandardfile(String standardfile) {
        this.standardfile = standardfile;
    }
}