package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysEvaluationFormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public SysEvaluationFormExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("se.ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("se.ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("se.ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("se.ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("se.ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("se.ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("se.ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("se.ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("se.ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("se.ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("se.ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("se.ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("se.ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("se.ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("se.name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("se.name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("se.name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("se.name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("se.name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("se.name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("se.name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("se.name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("se.name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("se.name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("se.name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("se.name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("se.name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("se.name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSerialIsNull() {
            addCriterion("se.Serial is null");
            return (Criteria) this;
        }

        public Criteria andSerialIsNotNull() {
            addCriterion("se.Serial is not null");
            return (Criteria) this;
        }

        public Criteria andSerialEqualTo(String value) {
            addCriterion("se.Serial =", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotEqualTo(String value) {
            addCriterion("se.Serial <>", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThan(String value) {
            addCriterion("se.Serial >", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThanOrEqualTo(String value) {
            addCriterion("se.Serial >=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThan(String value) {
            addCriterion("se.Serial <", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThanOrEqualTo(String value) {
            addCriterion("se.Serial <=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLike(String value) {
            addCriterion("se.Serial like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotLike(String value) {
            addCriterion("se.Serial not like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialIn(List<String> values) {
            addCriterion("se.Serial in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotIn(List<String> values) {
            addCriterion("se.Serial not in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialBetween(String value1, String value2) {
            addCriterion("se.Serial between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotBetween(String value1, String value2) {
            addCriterion("se.Serial not between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("se.level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("se.level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("se.level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("se.level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("se.level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("se.level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("se.level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("se.level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("se.level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("se.level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("se.level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("se.level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("se.level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("se.level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("se.version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("se.version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("se.version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("se.version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("se.version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("se.version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("se.version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("se.version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("se.version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("se.version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("se.version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("se.version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("se.version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("se.version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("se.status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("se.status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("se.status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("se.status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("se.status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("se.status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("se.status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("se.status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("se.status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("se.status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("se.status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("se.status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("se.total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("se.total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Long value) {
            addCriterion("se.total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Long value) {
            addCriterion("se.total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Long value) {
            addCriterion("se.total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("se.total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Long value) {
            addCriterion("se.total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Long value) {
            addCriterion("se.total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Long> values) {
            addCriterion("se.total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Long> values) {
            addCriterion("se.total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Long value1, Long value2) {
            addCriterion("se.total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Long value1, Long value2) {
            addCriterion("se.total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andPassmarkIsNull() {
            addCriterion("se.passmark is null");
            return (Criteria) this;
        }

        public Criteria andPassmarkIsNotNull() {
            addCriterion("se.passmark is not null");
            return (Criteria) this;
        }

        public Criteria andPassmarkEqualTo(Long value) {
            addCriterion("se.passmark =", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkNotEqualTo(Long value) {
            addCriterion("se.passmark <>", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkGreaterThan(Long value) {
            addCriterion("se.passmark >", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkGreaterThanOrEqualTo(Long value) {
            addCriterion("se.passmark >=", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkLessThan(Long value) {
            addCriterion("se.passmark <", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkLessThanOrEqualTo(Long value) {
            addCriterion("se.passmark <=", value, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkIn(List<Long> values) {
            addCriterion("se.passmark in", values, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkNotIn(List<Long> values) {
            addCriterion("se.passmark not in", values, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkBetween(Long value1, Long value2) {
            addCriterion("se.passmark between", value1, value2, "passmark");
            return (Criteria) this;
        }

        public Criteria andPassmarkNotBetween(Long value1, Long value2) {
            addCriterion("se.passmark not between", value1, value2, "passmark");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberIsNull() {
            addCriterion("se.judgesNumber is null");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberIsNotNull() {
            addCriterion("se.judgesNumber is not null");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberEqualTo(Integer value) {
            addCriterion("se.judgesNumber =", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberNotEqualTo(Integer value) {
            addCriterion("se.judgesNumber <>", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberGreaterThan(Integer value) {
            addCriterion("se.judgesNumber >", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("se.judgesNumber >=", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberLessThan(Integer value) {
            addCriterion("se.judgesNumber <", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberLessThanOrEqualTo(Integer value) {
            addCriterion("se.judgesNumber <=", value, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberIn(List<Integer> values) {
            addCriterion("se.judgesNumber in", values, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberNotIn(List<Integer> values) {
            addCriterion("se.judgesNumber not in", values, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberBetween(Integer value1, Integer value2) {
            addCriterion("se.judgesNumber between", value1, value2, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andJudgesnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("se.judgesNumber not between", value1, value2, "judgesnumber");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIsNull() {
            addCriterion("se.DateTimeCreated is null");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIsNotNull() {
            addCriterion("se.DateTimeCreated is not null");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedEqualTo(Date value) {
            addCriterion("se.DateTimeCreated =", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotEqualTo(Date value) {
            addCriterion("se.DateTimeCreated <>", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedGreaterThan(Date value) {
            addCriterion("se.DateTimeCreated >", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("se.DateTimeCreated >=", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedLessThan(Date value) {
            addCriterion("se.DateTimeCreated <", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
            addCriterion("se.DateTimeCreated <=", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIn(List<Date> values) {
            addCriterion("se.DateTimeCreated in", values, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotIn(List<Date> values) {
            addCriterion("se.DateTimeCreated not in", values, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
            addCriterion("se.DateTimeCreated between", value1, value2, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
            addCriterion("se.DateTimeCreated not between", value1, value2, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIsNull() {
            addCriterion("se.DateTimeModified is null");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIsNotNull() {
            addCriterion("se.DateTimeModified is not null");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedEqualTo(Date value) {
            addCriterion("se.DateTimeModified =", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotEqualTo(Date value) {
            addCriterion("se.DateTimeModified <>", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedGreaterThan(Date value) {
            addCriterion("se.DateTimeModified >", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("se.DateTimeModified >=", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedLessThan(Date value) {
            addCriterion("se.DateTimeModified <", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
            addCriterion("se.DateTimeModified <=", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIn(List<Date> values) {
            addCriterion("se.DateTimeModified in", values, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotIn(List<Date> values) {
            addCriterion("se.DateTimeModified not in", values, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
            addCriterion("se.DateTimeModified between", value1, value2, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
            addCriterion("se.DateTimeModified not between", value1, value2, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("se.isDeleted is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("se.isDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(Boolean value) {
            addCriterion("se.isDeleted =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(Boolean value) {
            addCriterion("se.isDeleted <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(Boolean value) {
            addCriterion("se.isDeleted >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("se.isDeleted >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(Boolean value) {
            addCriterion("se.isDeleted <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("se.isDeleted <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<Boolean> values) {
            addCriterion("se.isDeleted in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<Boolean> values) {
            addCriterion("se.isDeleted not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("se.isDeleted between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("se.isDeleted not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andStandardfileIsNull() {
            addCriterion("se.standardFile is null");
            return (Criteria) this;
        }

        public Criteria andStandardfileIsNotNull() {
            addCriterion("se.standardFile is not null");
            return (Criteria) this;
        }

        public Criteria andStandardfileEqualTo(String value) {
            addCriterion("se.standardFile =", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileNotEqualTo(String value) {
            addCriterion("se.standardFile <>", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileGreaterThan(String value) {
            addCriterion("se.standardFile >", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileGreaterThanOrEqualTo(String value) {
            addCriterion("se.standardFile >=", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileLessThan(String value) {
            addCriterion("se.standardFile <", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileLessThanOrEqualTo(String value) {
            addCriterion("se.standardFile <=", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileLike(String value) {
            addCriterion("se.standardFile like", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileNotLike(String value) {
            addCriterion("se.standardFile not like", value, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileIn(List<String> values) {
            addCriterion("se.standardFile in", values, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileNotIn(List<String> values) {
            addCriterion("se.standardFile not in", values, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileBetween(String value1, String value2) {
            addCriterion("se.standardFile between", value1, value2, "standardfile");
            return (Criteria) this;
        }

        public Criteria andStandardfileNotBetween(String value1, String value2) {
            addCriterion("se.standardFile not between", value1, value2, "standardfile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 18 13:39:02 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_evaluationform
     *
     * @mbggenerated Mon Sep 18 13:39:02 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}