package com.dynastech.model.entity;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.ID
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.userId
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.userName
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.type
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.level
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.msg
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.createdTime
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    private Date createdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.ID
     *
     * @return the value of SYS_LOG.ID
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.ID
     *
     * @param id the value for SYS_LOG.ID
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.userId
     *
     * @return the value of SYS_LOG.userId
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.userId
     *
     * @param userid the value for SYS_LOG.userId
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.userName
     *
     * @return the value of SYS_LOG.userName
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.userName
     *
     * @param username the value for SYS_LOG.userName
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.type
     *
     * @return the value of SYS_LOG.type
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.type
     *
     * @param type the value for SYS_LOG.type
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.level
     *
     * @return the value of SYS_LOG.level
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.level
     *
     * @param level the value for SYS_LOG.level
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.msg
     *
     * @return the value of SYS_LOG.msg
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.msg
     *
     * @param msg the value for SYS_LOG.msg
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.createdTime
     *
     * @return the value of SYS_LOG.createdTime
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.createdTime
     *
     * @param createdtime the value for SYS_LOG.createdTime
     *
     * @mbggenerated Fri Sep 15 16:38:44 CST 2017
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
}