package com.dynastech.model.entity;

public class UserPostInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.userId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.JobsTypeId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String jobstypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.JobsType
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String jobstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.JobsGrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String jobsgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.havequalificationseqID
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String havequalificationseqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.havequalificationseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String havequalificationseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.havequalificationgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String havequalificationgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.havequalificationgradeTime
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String havequalificationgradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.workconditionsseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String workconditionsseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.workconditionsgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String workconditionsgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.workconditionsgradeAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String workconditionsgradeannual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.nuclearresultsfront
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private Boolean nuclearresultsfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.nuclearresultsfrontAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String nuclearresultsfrontannual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.improvementplanclosedloop
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private Boolean improvementplanclosedloop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.graduateschool
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String graduateschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.majors
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String majors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.educational
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String educational;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_USER_POST_INFO.degree
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    private String degree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.userId
     *
     * @return the value of RS_USER_POST_INFO.userId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.userId
     *
     * @param userid the value for RS_USER_POST_INFO.userId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.JobsTypeId
     *
     * @return the value of RS_USER_POST_INFO.JobsTypeId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getJobstypeid() {
        return jobstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.JobsTypeId
     *
     * @param jobstypeid the value for RS_USER_POST_INFO.JobsTypeId
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setJobstypeid(String jobstypeid) {
        this.jobstypeid = jobstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.JobsType
     *
     * @return the value of RS_USER_POST_INFO.JobsType
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getJobstype() {
        return jobstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.JobsType
     *
     * @param jobstype the value for RS_USER_POST_INFO.JobsType
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setJobstype(String jobstype) {
        this.jobstype = jobstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.JobsGrade
     *
     * @return the value of RS_USER_POST_INFO.JobsGrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getJobsgrade() {
        return jobsgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.JobsGrade
     *
     * @param jobsgrade the value for RS_USER_POST_INFO.JobsGrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setJobsgrade(String jobsgrade) {
        this.jobsgrade = jobsgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.havequalificationseqID
     *
     * @return the value of RS_USER_POST_INFO.havequalificationseqID
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getHavequalificationseqid() {
        return havequalificationseqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.havequalificationseqID
     *
     * @param havequalificationseqid the value for RS_USER_POST_INFO.havequalificationseqID
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setHavequalificationseqid(String havequalificationseqid) {
        this.havequalificationseqid = havequalificationseqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.havequalificationseq
     *
     * @return the value of RS_USER_POST_INFO.havequalificationseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getHavequalificationseq() {
        return havequalificationseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.havequalificationseq
     *
     * @param havequalificationseq the value for RS_USER_POST_INFO.havequalificationseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setHavequalificationseq(String havequalificationseq) {
        this.havequalificationseq = havequalificationseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.havequalificationgrade
     *
     * @return the value of RS_USER_POST_INFO.havequalificationgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getHavequalificationgrade() {
        return havequalificationgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.havequalificationgrade
     *
     * @param havequalificationgrade the value for RS_USER_POST_INFO.havequalificationgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setHavequalificationgrade(String havequalificationgrade) {
        this.havequalificationgrade = havequalificationgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.havequalificationgradeTime
     *
     * @return the value of RS_USER_POST_INFO.havequalificationgradeTime
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getHavequalificationgradetime() {
        return havequalificationgradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.havequalificationgradeTime
     *
     * @param havequalificationgradetime the value for RS_USER_POST_INFO.havequalificationgradeTime
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setHavequalificationgradetime(String havequalificationgradetime) {
        this.havequalificationgradetime = havequalificationgradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.workconditionsseq
     *
     * @return the value of RS_USER_POST_INFO.workconditionsseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getWorkconditionsseq() {
        return workconditionsseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.workconditionsseq
     *
     * @param workconditionsseq the value for RS_USER_POST_INFO.workconditionsseq
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setWorkconditionsseq(String workconditionsseq) {
        this.workconditionsseq = workconditionsseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.workconditionsgrade
     *
     * @return the value of RS_USER_POST_INFO.workconditionsgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getWorkconditionsgrade() {
        return workconditionsgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.workconditionsgrade
     *
     * @param workconditionsgrade the value for RS_USER_POST_INFO.workconditionsgrade
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setWorkconditionsgrade(String workconditionsgrade) {
        this.workconditionsgrade = workconditionsgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.workconditionsgradeAnnual
     *
     * @return the value of RS_USER_POST_INFO.workconditionsgradeAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getWorkconditionsgradeannual() {
        return workconditionsgradeannual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.workconditionsgradeAnnual
     *
     * @param workconditionsgradeannual the value for RS_USER_POST_INFO.workconditionsgradeAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setWorkconditionsgradeannual(String workconditionsgradeannual) {
        this.workconditionsgradeannual = workconditionsgradeannual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.nuclearresultsfront
     *
     * @return the value of RS_USER_POST_INFO.nuclearresultsfront
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public Boolean getNuclearresultsfront() {
        return nuclearresultsfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.nuclearresultsfront
     *
     * @param nuclearresultsfront the value for RS_USER_POST_INFO.nuclearresultsfront
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setNuclearresultsfront(Boolean nuclearresultsfront) {
        this.nuclearresultsfront = nuclearresultsfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.nuclearresultsfrontAnnual
     *
     * @return the value of RS_USER_POST_INFO.nuclearresultsfrontAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getNuclearresultsfrontannual() {
        return nuclearresultsfrontannual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.nuclearresultsfrontAnnual
     *
     * @param nuclearresultsfrontannual the value for RS_USER_POST_INFO.nuclearresultsfrontAnnual
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setNuclearresultsfrontannual(String nuclearresultsfrontannual) {
        this.nuclearresultsfrontannual = nuclearresultsfrontannual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.improvementplanclosedloop
     *
     * @return the value of RS_USER_POST_INFO.improvementplanclosedloop
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public Boolean getImprovementplanclosedloop() {
        return improvementplanclosedloop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.improvementplanclosedloop
     *
     * @param improvementplanclosedloop the value for RS_USER_POST_INFO.improvementplanclosedloop
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setImprovementplanclosedloop(Boolean improvementplanclosedloop) {
        this.improvementplanclosedloop = improvementplanclosedloop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.graduateschool
     *
     * @return the value of RS_USER_POST_INFO.graduateschool
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getGraduateschool() {
        return graduateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.graduateschool
     *
     * @param graduateschool the value for RS_USER_POST_INFO.graduateschool
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setGraduateschool(String graduateschool) {
        this.graduateschool = graduateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.majors
     *
     * @return the value of RS_USER_POST_INFO.majors
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getMajors() {
        return majors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.majors
     *
     * @param majors the value for RS_USER_POST_INFO.majors
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setMajors(String majors) {
        this.majors = majors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.educational
     *
     * @return the value of RS_USER_POST_INFO.educational
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getEducational() {
        return educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.educational
     *
     * @param educational the value for RS_USER_POST_INFO.educational
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setEducational(String educational) {
        this.educational = educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_USER_POST_INFO.degree
     *
     * @return the value of RS_USER_POST_INFO.degree
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_USER_POST_INFO.degree
     *
     * @param degree the value for RS_USER_POST_INFO.degree
     *
     * @mbggenerated Thu Nov 30 15:28:03 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }
}