package com.data.model.mapper;

import com.data.model.entity.VUserPostInfo;
import com.data.model.entity.VUserPostInfoExample;
import java.util.List;

public interface VUserPostInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	int countByExample(VUserPostInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	List<VUserPostInfo> selectByExample(VUserPostInfoExample example);
}