package com.data.model.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VUserPostInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public VUserPostInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUseridIsNull() {
			addCriterion("vi.USERID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("vi.USERID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("vi.USERID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("vi.USERID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("vi.USERID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("vi.USERID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("vi.USERID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("vi.USERID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("vi.USERID like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("vi.USERID not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("vi.USERID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("vi.USERID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("vi.USERID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("vi.USERID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidIsNull() {
			addCriterion("vi.JOBSTYPEID is null");
			return (Criteria) this;
		}

		public Criteria andJobstypeidIsNotNull() {
			addCriterion("vi.JOBSTYPEID is not null");
			return (Criteria) this;
		}

		public Criteria andJobstypeidEqualTo(String value) {
			addCriterion("vi.JOBSTYPEID =", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidNotEqualTo(String value) {
			addCriterion("vi.JOBSTYPEID <>", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidGreaterThan(String value) {
			addCriterion("vi.JOBSTYPEID >", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidGreaterThanOrEqualTo(String value) {
			addCriterion("vi.JOBSTYPEID >=", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidLessThan(String value) {
			addCriterion("vi.JOBSTYPEID <", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidLessThanOrEqualTo(String value) {
			addCriterion("vi.JOBSTYPEID <=", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidLike(String value) {
			addCriterion("vi.JOBSTYPEID like", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidNotLike(String value) {
			addCriterion("vi.JOBSTYPEID not like", value, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidIn(List<String> values) {
			addCriterion("vi.JOBSTYPEID in", values, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidNotIn(List<String> values) {
			addCriterion("vi.JOBSTYPEID not in", values, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidBetween(String value1, String value2) {
			addCriterion("vi.JOBSTYPEID between", value1, value2, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeidNotBetween(String value1, String value2) {
			addCriterion("vi.JOBSTYPEID not between", value1, value2, "jobstypeid");
			return (Criteria) this;
		}

		public Criteria andJobstypeIsNull() {
			addCriterion("vi.JOBSTYPE is null");
			return (Criteria) this;
		}

		public Criteria andJobstypeIsNotNull() {
			addCriterion("vi.JOBSTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andJobstypeEqualTo(String value) {
			addCriterion("vi.JOBSTYPE =", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeNotEqualTo(String value) {
			addCriterion("vi.JOBSTYPE <>", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeGreaterThan(String value) {
			addCriterion("vi.JOBSTYPE >", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.JOBSTYPE >=", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeLessThan(String value) {
			addCriterion("vi.JOBSTYPE <", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeLessThanOrEqualTo(String value) {
			addCriterion("vi.JOBSTYPE <=", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeLike(String value) {
			addCriterion("vi.JOBSTYPE like", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeNotLike(String value) {
			addCriterion("vi.JOBSTYPE not like", value, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeIn(List<String> values) {
			addCriterion("vi.JOBSTYPE in", values, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeNotIn(List<String> values) {
			addCriterion("vi.JOBSTYPE not in", values, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeBetween(String value1, String value2) {
			addCriterion("vi.JOBSTYPE between", value1, value2, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobstypeNotBetween(String value1, String value2) {
			addCriterion("vi.JOBSTYPE not between", value1, value2, "jobstype");
			return (Criteria) this;
		}

		public Criteria andJobsgradeIsNull() {
			addCriterion("vi.JOBSGRADE is null");
			return (Criteria) this;
		}

		public Criteria andJobsgradeIsNotNull() {
			addCriterion("vi.JOBSGRADE is not null");
			return (Criteria) this;
		}

		public Criteria andJobsgradeEqualTo(String value) {
			addCriterion("vi.JOBSGRADE =", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeNotEqualTo(String value) {
			addCriterion("vi.JOBSGRADE <>", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeGreaterThan(String value) {
			addCriterion("vi.JOBSGRADE >", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.JOBSGRADE >=", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeLessThan(String value) {
			addCriterion("vi.JOBSGRADE <", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeLessThanOrEqualTo(String value) {
			addCriterion("vi.JOBSGRADE <=", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeLike(String value) {
			addCriterion("vi.JOBSGRADE like", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeNotLike(String value) {
			addCriterion("vi.JOBSGRADE not like", value, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeIn(List<String> values) {
			addCriterion("vi.JOBSGRADE in", values, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeNotIn(List<String> values) {
			addCriterion("vi.JOBSGRADE not in", values, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeBetween(String value1, String value2) {
			addCriterion("vi.JOBSGRADE between", value1, value2, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andJobsgradeNotBetween(String value1, String value2) {
			addCriterion("vi.JOBSGRADE not between", value1, value2, "jobsgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidIsNull() {
			addCriterion("vi.HAVEQUALIFICATIONSEQID is null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidIsNotNull() {
			addCriterion("vi.HAVEQUALIFICATIONSEQID is not null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID =", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidNotEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID <>", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidGreaterThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID >", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidGreaterThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID >=", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidLessThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID <", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidLessThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID <=", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID like", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidNotLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID not like", value, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID in", values, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidNotIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID not in", values, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID between", value1, value2, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqidNotBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONSEQID not between", value1, value2, "havequalificationseqid");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqIsNull() {
			addCriterion("vi.HAVEQUALIFICATIONSEQ is null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqIsNotNull() {
			addCriterion("vi.HAVEQUALIFICATIONSEQ is not null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ =", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqNotEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ <>", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqGreaterThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ >", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqGreaterThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ >=", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqLessThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ <", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqLessThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ <=", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ like", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqNotLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ not like", value, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ in", values, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqNotIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ not in", values, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ between", value1, value2, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationseqNotBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONSEQ not between", value1, value2, "havequalificationseq");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeIsNull() {
			addCriterion("vi.HAVEQUALIFICATIONGRADE is null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeIsNotNull() {
			addCriterion("vi.HAVEQUALIFICATIONGRADE is not null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE =", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeNotEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE <>", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeGreaterThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE >", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE >=", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeLessThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE <", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeLessThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE <=", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE like", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeNotLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE not like", value, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE in", values, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeNotIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE not in", values, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE between", value1, value2, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradeNotBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONGRADE not between", value1, value2, "havequalificationgrade");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeIsNull() {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME is null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeIsNotNull() {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME is not null");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME =", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeNotEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME <>", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeGreaterThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME >", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME >=", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeLessThan(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME <", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeLessThanOrEqualTo(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME <=", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME like", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeNotLike(String value) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME not like", value, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME in", values, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeNotIn(List<String> values) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME not in", values, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME between", value1, value2, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andHavequalificationgradetimeNotBetween(String value1, String value2) {
			addCriterion("vi.HAVEQUALIFICATIONGRADETIME not between", value1, value2, "havequalificationgradetime");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqIsNull() {
			addCriterion("vi.WORKCONDITIONSSEQ is null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqIsNotNull() {
			addCriterion("vi.WORKCONDITIONSSEQ is not null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ =", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqNotEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ <>", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqGreaterThan(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ >", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqGreaterThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ >=", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqLessThan(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ <", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqLessThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ <=", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqLike(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ like", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqNotLike(String value) {
			addCriterion("vi.WORKCONDITIONSSEQ not like", value, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSSEQ in", values, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqNotIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSSEQ not in", values, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSSEQ between", value1, value2, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsseqNotBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSSEQ not between", value1, value2, "workconditionsseq");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeIsNull() {
			addCriterion("vi.WORKCONDITIONSGRADE is null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeIsNotNull() {
			addCriterion("vi.WORKCONDITIONSGRADE is not null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE =", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeNotEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE <>", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeGreaterThan(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE >", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE >=", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeLessThan(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE <", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeLessThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE <=", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeLike(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE like", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeNotLike(String value) {
			addCriterion("vi.WORKCONDITIONSGRADE not like", value, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSGRADE in", values, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeNotIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSGRADE not in", values, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSGRADE between", value1, value2, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeNotBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSGRADE not between", value1, value2, "workconditionsgrade");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualIsNull() {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL is null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualIsNotNull() {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL is not null");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL =", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualNotEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL <>", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualGreaterThan(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL >", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualGreaterThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL >=", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualLessThan(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL <", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualLessThanOrEqualTo(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL <=", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualLike(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL like", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualNotLike(String value) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL not like", value, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL in", values, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualNotIn(List<String> values) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL not in", values, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL between", value1, value2, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andWorkconditionsgradeannualNotBetween(String value1, String value2) {
			addCriterion("vi.WORKCONDITIONSGRADEANNUAL not between", value1, value2, "workconditionsgradeannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontIsNull() {
			addCriterion("vi.NUCLEARRESULTSFRONT is null");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontIsNotNull() {
			addCriterion("vi.NUCLEARRESULTSFRONT is not null");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT =", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontNotEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT <>", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontGreaterThan(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT >", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontGreaterThanOrEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT >=", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontLessThan(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT <", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontLessThanOrEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT <=", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontLike(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT like", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontNotLike(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONT not like", value, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontIn(List<String> values) {
			addCriterion("vi.NUCLEARRESULTSFRONT in", values, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontNotIn(List<String> values) {
			addCriterion("vi.NUCLEARRESULTSFRONT not in", values, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontBetween(String value1, String value2) {
			addCriterion("vi.NUCLEARRESULTSFRONT between", value1, value2, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontNotBetween(String value1, String value2) {
			addCriterion("vi.NUCLEARRESULTSFRONT not between", value1, value2, "nuclearresultsfront");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualIsNull() {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL is null");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualIsNotNull() {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL is not null");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL =", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualNotEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL <>", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualGreaterThan(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL >", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualGreaterThanOrEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL >=", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualLessThan(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL <", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualLessThanOrEqualTo(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL <=", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualLike(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL like", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualNotLike(String value) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL not like", value, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualIn(List<String> values) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL in", values, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualNotIn(List<String> values) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL not in", values, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualBetween(String value1, String value2) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL between", value1, value2, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andNuclearresultsfrontannualNotBetween(String value1, String value2) {
			addCriterion("vi.NUCLEARRESULTSFRONTANNUAL not between", value1, value2, "nuclearresultsfrontannual");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopIsNull() {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP is null");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopIsNotNull() {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP is not null");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopEqualTo(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP =", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopNotEqualTo(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP <>", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopGreaterThan(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP >", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopGreaterThanOrEqualTo(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP >=", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopLessThan(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP <", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopLessThanOrEqualTo(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP <=", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopLike(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP like", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopNotLike(String value) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP not like", value, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopIn(List<String> values) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP in", values, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopNotIn(List<String> values) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP not in", values, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopBetween(String value1, String value2) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP between", value1, value2, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andImprovementplanclosedloopNotBetween(String value1, String value2) {
			addCriterion("vi.IMPROVEMENTPLANCLOSEDLOOP not between", value1, value2, "improvementplanclosedloop");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolIsNull() {
			addCriterion("vi.GRADUATESCHOOL is null");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolIsNotNull() {
			addCriterion("vi.GRADUATESCHOOL is not null");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolEqualTo(String value) {
			addCriterion("vi.GRADUATESCHOOL =", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolNotEqualTo(String value) {
			addCriterion("vi.GRADUATESCHOOL <>", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolGreaterThan(String value) {
			addCriterion("vi.GRADUATESCHOOL >", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolGreaterThanOrEqualTo(String value) {
			addCriterion("vi.GRADUATESCHOOL >=", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolLessThan(String value) {
			addCriterion("vi.GRADUATESCHOOL <", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolLessThanOrEqualTo(String value) {
			addCriterion("vi.GRADUATESCHOOL <=", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolLike(String value) {
			addCriterion("vi.GRADUATESCHOOL like", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolNotLike(String value) {
			addCriterion("vi.GRADUATESCHOOL not like", value, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolIn(List<String> values) {
			addCriterion("vi.GRADUATESCHOOL in", values, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolNotIn(List<String> values) {
			addCriterion("vi.GRADUATESCHOOL not in", values, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolBetween(String value1, String value2) {
			addCriterion("vi.GRADUATESCHOOL between", value1, value2, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andGraduateschoolNotBetween(String value1, String value2) {
			addCriterion("vi.GRADUATESCHOOL not between", value1, value2, "graduateschool");
			return (Criteria) this;
		}

		public Criteria andMajorsIsNull() {
			addCriterion("vi.MAJORS is null");
			return (Criteria) this;
		}

		public Criteria andMajorsIsNotNull() {
			addCriterion("vi.MAJORS is not null");
			return (Criteria) this;
		}

		public Criteria andMajorsEqualTo(String value) {
			addCriterion("vi.MAJORS =", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsNotEqualTo(String value) {
			addCriterion("vi.MAJORS <>", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsGreaterThan(String value) {
			addCriterion("vi.MAJORS >", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsGreaterThanOrEqualTo(String value) {
			addCriterion("vi.MAJORS >=", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsLessThan(String value) {
			addCriterion("vi.MAJORS <", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsLessThanOrEqualTo(String value) {
			addCriterion("vi.MAJORS <=", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsLike(String value) {
			addCriterion("vi.MAJORS like", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsNotLike(String value) {
			addCriterion("vi.MAJORS not like", value, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsIn(List<String> values) {
			addCriterion("vi.MAJORS in", values, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsNotIn(List<String> values) {
			addCriterion("vi.MAJORS not in", values, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsBetween(String value1, String value2) {
			addCriterion("vi.MAJORS between", value1, value2, "majors");
			return (Criteria) this;
		}

		public Criteria andMajorsNotBetween(String value1, String value2) {
			addCriterion("vi.MAJORS not between", value1, value2, "majors");
			return (Criteria) this;
		}

		public Criteria andEducationalIsNull() {
			addCriterion("vi.EDUCATIONAL is null");
			return (Criteria) this;
		}

		public Criteria andEducationalIsNotNull() {
			addCriterion("vi.EDUCATIONAL is not null");
			return (Criteria) this;
		}

		public Criteria andEducationalEqualTo(String value) {
			addCriterion("vi.EDUCATIONAL =", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalNotEqualTo(String value) {
			addCriterion("vi.EDUCATIONAL <>", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalGreaterThan(String value) {
			addCriterion("vi.EDUCATIONAL >", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalGreaterThanOrEqualTo(String value) {
			addCriterion("vi.EDUCATIONAL >=", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalLessThan(String value) {
			addCriterion("vi.EDUCATIONAL <", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalLessThanOrEqualTo(String value) {
			addCriterion("vi.EDUCATIONAL <=", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalLike(String value) {
			addCriterion("vi.EDUCATIONAL like", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalNotLike(String value) {
			addCriterion("vi.EDUCATIONAL not like", value, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalIn(List<String> values) {
			addCriterion("vi.EDUCATIONAL in", values, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalNotIn(List<String> values) {
			addCriterion("vi.EDUCATIONAL not in", values, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalBetween(String value1, String value2) {
			addCriterion("vi.EDUCATIONAL between", value1, value2, "educational");
			return (Criteria) this;
		}

		public Criteria andEducationalNotBetween(String value1, String value2) {
			addCriterion("vi.EDUCATIONAL not between", value1, value2, "educational");
			return (Criteria) this;
		}

		public Criteria andDegreeIsNull() {
			addCriterion("vi.DEGREE is null");
			return (Criteria) this;
		}

		public Criteria andDegreeIsNotNull() {
			addCriterion("vi.DEGREE is not null");
			return (Criteria) this;
		}

		public Criteria andDegreeEqualTo(String value) {
			addCriterion("vi.DEGREE =", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotEqualTo(String value) {
			addCriterion("vi.DEGREE <>", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeGreaterThan(String value) {
			addCriterion("vi.DEGREE >", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeGreaterThanOrEqualTo(String value) {
			addCriterion("vi.DEGREE >=", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLessThan(String value) {
			addCriterion("vi.DEGREE <", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLessThanOrEqualTo(String value) {
			addCriterion("vi.DEGREE <=", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeLike(String value) {
			addCriterion("vi.DEGREE like", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotLike(String value) {
			addCriterion("vi.DEGREE not like", value, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeIn(List<String> values) {
			addCriterion("vi.DEGREE in", values, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotIn(List<String> values) {
			addCriterion("vi.DEGREE not in", values, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeBetween(String value1, String value2) {
			addCriterion("vi.DEGREE between", value1, value2, "degree");
			return (Criteria) this;
		}

		public Criteria andDegreeNotBetween(String value1, String value2) {
			addCriterion("vi.DEGREE not between", value1, value2, "degree");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table V_USER_POST_INFO
	 * @mbggenerated  Mon Dec 04 11:43:33 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table V_USER_POST_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 30 10:04:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}