package com.dynastech.user.entity;

import java.util.Date;

public class UserResume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.ID
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.education
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.WorkResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String workresume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.speciality
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String speciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.honor
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String honor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.programme
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private String programme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.DateTimeCreated
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private Date datetimecreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RS_UserResume.DateTimeModified
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    private Date datetimemodified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.ID
     *
     * @return the value of RS_UserResume.ID
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.ID
     *
     * @param id the value for RS_UserResume.ID
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.education
     *
     * @return the value of RS_UserResume.education
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.education
     *
     * @param education the value for RS_UserResume.education
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.WorkResume
     *
     * @return the value of RS_UserResume.WorkResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getWorkresume() {
        return workresume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.WorkResume
     *
     * @param workresume the value for RS_UserResume.WorkResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setWorkresume(String workresume) {
        this.workresume = workresume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.speciality
     *
     * @return the value of RS_UserResume.speciality
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.speciality
     *
     * @param speciality the value for RS_UserResume.speciality
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.honor
     *
     * @return the value of RS_UserResume.honor
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.honor
     *
     * @param honor the value for RS_UserResume.honor
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setHonor(String honor) {
        this.honor = honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.programme
     *
     * @return the value of RS_UserResume.programme
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getProgramme() {
        return programme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.programme
     *
     * @param programme the value for RS_UserResume.programme
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setProgramme(String programme) {
        this.programme = programme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.DateTimeCreated
     *
     * @return the value of RS_UserResume.DateTimeCreated
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public Date getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.DateTimeCreated
     *
     * @param datetimecreated the value for RS_UserResume.DateTimeCreated
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setDatetimecreated(Date datetimecreated) {
        this.datetimecreated = datetimecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RS_UserResume.DateTimeModified
     *
     * @return the value of RS_UserResume.DateTimeModified
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public Date getDatetimemodified() {
        return datetimemodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RS_UserResume.DateTimeModified
     *
     * @param datetimemodified the value for RS_UserResume.DateTimeModified
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setDatetimemodified(Date datetimemodified) {
        this.datetimemodified = datetimemodified;
    }
}