package com.dynastech.user.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserResumeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public UserResumeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ur.ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ur.ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ur.ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ur.ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ur.ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ur.ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ur.ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ur.ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ur.ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ur.ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ur.ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ur.ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ur.ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ur.ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEducationIsNull() {
            addCriterion("ur.education is null");
            return (Criteria) this;
        }

        public Criteria andEducationIsNotNull() {
            addCriterion("ur.education is not null");
            return (Criteria) this;
        }

        public Criteria andEducationEqualTo(String value) {
            addCriterion("ur.education =", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotEqualTo(String value) {
            addCriterion("ur.education <>", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThan(String value) {
            addCriterion("ur.education >", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThanOrEqualTo(String value) {
            addCriterion("ur.education >=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThan(String value) {
            addCriterion("ur.education <", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThanOrEqualTo(String value) {
            addCriterion("ur.education <=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLike(String value) {
            addCriterion("ur.education like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotLike(String value) {
            addCriterion("ur.education not like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationIn(List<String> values) {
            addCriterion("ur.education in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotIn(List<String> values) {
            addCriterion("ur.education not in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationBetween(String value1, String value2) {
            addCriterion("ur.education between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotBetween(String value1, String value2) {
            addCriterion("ur.education not between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andWorkresumeIsNull() {
            addCriterion("ur.WorkResume is null");
            return (Criteria) this;
        }

        public Criteria andWorkresumeIsNotNull() {
            addCriterion("ur.WorkResume is not null");
            return (Criteria) this;
        }

        public Criteria andWorkresumeEqualTo(String value) {
            addCriterion("ur.WorkResume =", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeNotEqualTo(String value) {
            addCriterion("ur.WorkResume <>", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeGreaterThan(String value) {
            addCriterion("ur.WorkResume >", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeGreaterThanOrEqualTo(String value) {
            addCriterion("ur.WorkResume >=", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeLessThan(String value) {
            addCriterion("ur.WorkResume <", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeLessThanOrEqualTo(String value) {
            addCriterion("ur.WorkResume <=", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeLike(String value) {
            addCriterion("ur.WorkResume like", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeNotLike(String value) {
            addCriterion("ur.WorkResume not like", value, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeIn(List<String> values) {
            addCriterion("ur.WorkResume in", values, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeNotIn(List<String> values) {
            addCriterion("ur.WorkResume not in", values, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeBetween(String value1, String value2) {
            addCriterion("ur.WorkResume between", value1, value2, "workresume");
            return (Criteria) this;
        }

        public Criteria andWorkresumeNotBetween(String value1, String value2) {
            addCriterion("ur.WorkResume not between", value1, value2, "workresume");
            return (Criteria) this;
        }

        public Criteria andSpecialityIsNull() {
            addCriterion("ur.speciality is null");
            return (Criteria) this;
        }

        public Criteria andSpecialityIsNotNull() {
            addCriterion("ur.speciality is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialityEqualTo(String value) {
            addCriterion("ur.speciality =", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityNotEqualTo(String value) {
            addCriterion("ur.speciality <>", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityGreaterThan(String value) {
            addCriterion("ur.speciality >", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityGreaterThanOrEqualTo(String value) {
            addCriterion("ur.speciality >=", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityLessThan(String value) {
            addCriterion("ur.speciality <", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityLessThanOrEqualTo(String value) {
            addCriterion("ur.speciality <=", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityLike(String value) {
            addCriterion("ur.speciality like", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityNotLike(String value) {
            addCriterion("ur.speciality not like", value, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityIn(List<String> values) {
            addCriterion("ur.speciality in", values, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityNotIn(List<String> values) {
            addCriterion("ur.speciality not in", values, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityBetween(String value1, String value2) {
            addCriterion("ur.speciality between", value1, value2, "speciality");
            return (Criteria) this;
        }

        public Criteria andSpecialityNotBetween(String value1, String value2) {
            addCriterion("ur.speciality not between", value1, value2, "speciality");
            return (Criteria) this;
        }

        public Criteria andHonorIsNull() {
            addCriterion("ur.honor is null");
            return (Criteria) this;
        }

        public Criteria andHonorIsNotNull() {
            addCriterion("ur.honor is not null");
            return (Criteria) this;
        }

        public Criteria andHonorEqualTo(String value) {
            addCriterion("ur.honor =", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorNotEqualTo(String value) {
            addCriterion("ur.honor <>", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorGreaterThan(String value) {
            addCriterion("ur.honor >", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorGreaterThanOrEqualTo(String value) {
            addCriterion("ur.honor >=", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorLessThan(String value) {
            addCriterion("ur.honor <", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorLessThanOrEqualTo(String value) {
            addCriterion("ur.honor <=", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorLike(String value) {
            addCriterion("ur.honor like", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorNotLike(String value) {
            addCriterion("ur.honor not like", value, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorIn(List<String> values) {
            addCriterion("ur.honor in", values, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorNotIn(List<String> values) {
            addCriterion("ur.honor not in", values, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorBetween(String value1, String value2) {
            addCriterion("ur.honor between", value1, value2, "honor");
            return (Criteria) this;
        }

        public Criteria andHonorNotBetween(String value1, String value2) {
            addCriterion("ur.honor not between", value1, value2, "honor");
            return (Criteria) this;
        }

        public Criteria andProgrammeIsNull() {
            addCriterion("ur.programme is null");
            return (Criteria) this;
        }

        public Criteria andProgrammeIsNotNull() {
            addCriterion("ur.programme is not null");
            return (Criteria) this;
        }

        public Criteria andProgrammeEqualTo(String value) {
            addCriterion("ur.programme =", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotEqualTo(String value) {
            addCriterion("ur.programme <>", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeGreaterThan(String value) {
            addCriterion("ur.programme >", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeGreaterThanOrEqualTo(String value) {
            addCriterion("ur.programme >=", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLessThan(String value) {
            addCriterion("ur.programme <", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLessThanOrEqualTo(String value) {
            addCriterion("ur.programme <=", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLike(String value) {
            addCriterion("ur.programme like", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotLike(String value) {
            addCriterion("ur.programme not like", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeIn(List<String> values) {
            addCriterion("ur.programme in", values, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotIn(List<String> values) {
            addCriterion("ur.programme not in", values, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeBetween(String value1, String value2) {
            addCriterion("ur.programme between", value1, value2, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotBetween(String value1, String value2) {
            addCriterion("ur.programme not between", value1, value2, "programme");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIsNull() {
            addCriterion("ur.DateTimeCreated is null");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIsNotNull() {
            addCriterion("ur.DateTimeCreated is not null");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedEqualTo(Date value) {
            addCriterion("ur.DateTimeCreated =", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotEqualTo(Date value) {
            addCriterion("ur.DateTimeCreated <>", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedGreaterThan(Date value) {
            addCriterion("ur.DateTimeCreated >", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("ur.DateTimeCreated >=", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedLessThan(Date value) {
            addCriterion("ur.DateTimeCreated <", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
            addCriterion("ur.DateTimeCreated <=", value, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedIn(List<Date> values) {
            addCriterion("ur.DateTimeCreated in", values, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotIn(List<Date> values) {
            addCriterion("ur.DateTimeCreated not in", values, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
            addCriterion("ur.DateTimeCreated between", value1, value2, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
            addCriterion("ur.DateTimeCreated not between", value1, value2, "datetimecreated");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIsNull() {
            addCriterion("ur.DateTimeModified is null");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIsNotNull() {
            addCriterion("ur.DateTimeModified is not null");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedEqualTo(Date value) {
            addCriterion("ur.DateTimeModified =", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotEqualTo(Date value) {
            addCriterion("ur.DateTimeModified <>", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedGreaterThan(Date value) {
            addCriterion("ur.DateTimeModified >", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("ur.DateTimeModified >=", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedLessThan(Date value) {
            addCriterion("ur.DateTimeModified <", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
            addCriterion("ur.DateTimeModified <=", value, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedIn(List<Date> values) {
            addCriterion("ur.DateTimeModified in", values, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotIn(List<Date> values) {
            addCriterion("ur.DateTimeModified not in", values, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
            addCriterion("ur.DateTimeModified between", value1, value2, "datetimemodified");
            return (Criteria) this;
        }

        public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
            addCriterion("ur.DateTimeModified not between", value1, value2, "datetimemodified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RS_UserResume
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 25 16:46:52 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RS_UserResume
     *
     * @mbggenerated Fri Aug 25 16:46:52 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}